silence NPE error on cron triggered builds
When Cause.UserIdCause is null, this (non-fatal) error message is being
displayed in the build console:

    java.lang.NullPointerException: Cannot invoke method getUserId() on null object